### ISSUE TITLE
API地址已经失效，有最新的吗？

### ISSUE THREAD

**Issue by syh0304** [weituotian/youku_parse#1]
Fatal error: Uncaught exception 'Requests_Exception' with message 'cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received' in D:\AppServ\www\youkup\Requests-master\library\Requests\Transport\cURL.php:422 Stack trace: #0 D:\AppServ\www\youkup\Requests-master\library\Requests\Transport\cURL.php(177): Requests_Transport_cURL->process_response('', Array) #1 D:\AppServ\www\youkup\Requests-master\library\Requests.php(379): Requests_Transport_cURL->request('http://play-ali...', Array, NULL, Array) #2 D:\AppServ\www\youkup\Requests-master\library\Requests.php(231): Requests::request('http://play-ali...', Array, NULL, 'GET', Array) #3 D:\AppServ\www\youkup\main\class\VideoInfo.php(72): Requests::get('http://play-ali...', Array) #4 D:\AppServ\www\youkup\main\class\VideoInfo.php(29): VideoInfo->InitData() #5 D:\AppServ\www\youkup\main\index.php(23): VideoInfo->__construct('XMTczMzE5MTkwMA...') #6 {main} thrown in D:\AppServ\www\youkup\Requests-master\library\Requests\Transport\cURL.php on line 422

**Comment by weituotian** [comment]
准备重新分析js文件, 现在还不能搞定。

**Comment by weituotian** [comment]
2018/3/23，dev分支更新了

**Comment by wnpllrzodiac** [comment]
refer to you-get code

**Comment by weituotian** [comment]
@wnpllrzodiac it is right.

**Comment by thesongtao** [comment]
你好作者我想和你学习一下这个的分析过程,可以给我一个联系你的方式么我的q :919379479

**Comment by walkedSnail** [comment]
优酷视频不能解析的问题解决了吗
